name: publish npmjs and gh pages

on: push

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: Package versioning
        run: echo '::set-output name=PKG_VERSION::$(npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version)'
        id: package-version
      - run: npm publish ${{ steps.package-version.outputs.PKG_VERSION }}.tgz
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
